level0_map =[
'                                                                     M                                                  ',
'                                                        O  M  M   L  M O                                                ',
'Y                                                        QWWWWWWWWWWWWE                                                 ',
'STTY                                                     ASSSSSSSSSSSSD                                                 ',
'SSSGTY                                 M   M             ASSSSSSSSSSSSD                                                 ',
'SSSGSSTY                                                 ZSSSSSSSSSSSSD                                                 ',
'SSSGSSSD               O  M L O    O   M   M  MK O        ZSSSSSSSSSSSD                                                 ',
'SSSGSSSD                QWWWWE      RTTTTTTTTTTTTY         ZSSSSSSSSSSD                                                 ',
'SSSGSSSD                ASSSSD    RTSSSSSSSSSSSSSH          ZSSSSSSSSSC                                                 ',
'SSSGSSSD                ZXXXXC    FSSSSSSSSSSSSSSH           XXXXXXXXC              O    L    L  L  O                   ',
'SSSGSSSD                          VSSSSSSSSSSSSSSH                                   QWWWWWWWWWWWWWE                    ',
'SSGGSSSD                           VXXXXXXXXXXXXXC                                   ASSSSSSSSSSSSSD                    ',
'SSGGSSSD      O L M L  O                                                             ASSSSSSSSSSSSSD            O   I  O',
'SSGGSSSD       RTTTTTTY O  L   O                                                     ASSSSSSSSSSSSSC             RTTTTY ',
'SSGGSSSD U     FGGGGGGH  QWWWWE  O   L   O                           O  L   L  1  O  ASSSSSSSSSSSSC              VGGGGN ',
'SSGGSSSDQWWE   FGGGGGGH  ASSSSD   RTTTTTY                             QWWWTTTTTTTY   ASSSSSSSSSSSC                VBBN  ',
'SSGGSSSDASSD   FGGGGGGH  ZXXXXC   FGGGGGH                            RSSSSSSGGGGGH   ASSSSSSSSSSC                       ',
'SSGGSSSDASSD   FGGGGGGH           FGGGGGH O   L   L    L  ML  O     RSSSSSSSSSGGGH   ASSSSSSSSSC                        ',
'SSGGSSSDASSD   FGGGGGGH           FGGGGGH  RTTTTTTTTTTTTTTTTTY      FSSSSSSSSSGGGH   ASSSSSSSSC                         ',
'ZXXXXXXCZXXC   VBBBBBBN           VBBBBBN  FGGGGGGGGGGGGGGGGGH      FSSSSSSSSGGGGH   VXXXXXXXC                          ',
'ZXXXXXXCZXXC   VBBBBBBN           VBBBBBN  FGGGGGGGGGGGGGGGGGH      FSSSSSSSSGGGGH   VXXXXXXXC                          '
]

level1_map = [                                                                                                                                                                                                                                                                                                          
'E                                                                                                                                                                                                                                                                                                                ',
'DE                                                                                              O    M OO  ML  OO  M   OO  M   O    O   L  O                                                                                                                                                                    ',
'SDE                                              O  3   M          M                O            QWWWWE  QWWWWE  QWWWWE  QWWWWE      QWWWWE                                          .                                                                                                                          ',                                                                                
'SSDE                                              RTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTY             ASSSSD  ASSSSD  ASSSSD  ASSSSD      ASSSSD                        M                     M                                                                                                                      ',                                                                                
'SSSDE                                             FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY            ZXXXXC  ZXXXXC  ZXXXXC  ZXXXXC      ZXXXXC      O   L    M     K      L    O                            RTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTY                           ',                                                                                
'SSSSDQWWWWE                                       FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                             RTTTWWWWWWWWWWWWWWWWWWWWWE                 .          ASSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                           ',                                                                                
'SSSSDASSSSD                               .  .    FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                           RASSSSSSSSSSSSSSSSSSSSSSSSD    O K O                   RSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                           ',                                                                                
'SSSSDASSSSD                                       FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                          ASSSSSSSSSSSSSSSSSSSSSSSSSD     QWE J                  FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                    .      ',                                                                                
'SSSSDASSSSD                                  M    FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                         ASSSSSSSSSSSSSSSSSSSSSSSSSD     ASD                    FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                           ',                                                                                
'SSSSDASSSSD                               J       FSSSSSSSSSSSSSSSSSSSSSSSSSSBBBBBBSSSSSD                                                         ASSSSSSSSSSSSSSSSSSSSSSSSSD     ZXC                    FSSSSSSSSXXXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                           ',                                                                                
'SSSSDASSSSD                                       VSSSSSSSSSSSSSSSSSSSSSSSSSN      ZSSSSD        QE                                               ASSSSSSSSSSSSSSSSSSSSSSSSSD         . O K O            FSSSSSSXC   ZXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                           ',                                                                                
'SSSSDASSSSD      U  O    M         O      M  J     VSSSSSSSSSSSSSSSSSSSSSSSN        ZXXXC        ZC                                               ASSSSSSSSSSSSSSSSSSSSSSSSSD            QWE  J          FSSSSSD       ZXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                           ',                                                                                
'SSSSDASSSSD    QWWE QWWWWWWWWWWWWWE                 VSSSSSSSSSSSSSSSSSSSSSN                                                  O      L     M  2 O  ASSSSSSSSSSSSSSSSSSSSSSSSSD            ASD             FSSSSSSY        ZXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXSSSH                    J  I   ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD O     .  . O     VBBBBBBBBBBBBBBBBBBBN                                                    RWTWTTWTTTWWWTTTY   ASSSSSSSSSSSSSSSSSSSSSSSSSD            ZXC             VSSSSSSSY         ZXXXXXXXXXXXXXXXXXXXXXXXSSSXXXXSSSXXXXXXXXXXXXXXXXXXC  ZSSH                           ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  QWWWWWWWWE                                                              O    M  L    O   FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                  O K O      VBBBBBBC                                 ZXC    ZXC                      ZXC    O      L  M   O        ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  ASSSSSSSSDE                                              O    L M  O     QWWWWWWWWWWE    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                 . QWE                                                                                        RTTTTTWWWWWWE         ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  ASSSSSSSSSD                                               RTTWWWWWE      ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                   ASD                                                                                       RFSSSSSSSSSSSD         ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  ASSSSSSSSSCO    L    O       L   M       L   M      O    RSSSSSSSSD      ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                   ZXC                   M                 M             M                                  RFSSSSSSSSSSSSD  .      ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  ZSSSSSSSSC  QWWWWTTTY  RTTTTTTTTTTTTTTTTTTTTTTTTTTTY     FSSSSSSSSH      ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                        O     L   OO        L         L          O O        L    O                         RFSSSSSSSSSSSSSD         ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD   ZXXXXXXC   FGGGGGGGH  FSSSSSSSSSSSSSSSSSSSSSSSSSSSH     FSSSSSSSSH      ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                         QWWWWTTTY  RTTTTTTTTTTTTTTTTTTTTTTTTTTTY   RTTTTTTTTTTTY        M       M        RFSSSSSSSSSSSSSSD         ',                                                                                
'                                                                                                              ZXXXXXXXXXXC    VBBBBBBBBBBBBBBBN   VBXXXXXXXXXXXXXXXXXXXXXXXXC                         AGGGGGGGH  FSSSSSSSSSSSSSSSSSSSSSSSSSSSH   FSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTFSSSSSSSSSSSSSSSD         '                                                                                                                                                                    
]

level2_map = [
'W                                                                                         .                                                                                                                                                                .                                                ',
'S                                                                                                                                                                                                                                                                                                           ',
'S                                                                                                M                                                                        .                                                                                                                                 ',
'SWE                                                                                       J                                                                                                                                                                             .       4                           ',
'SSSE                                                           M   M    M  M           M         M                                                                                                                               M                                             QWE                          ',
'SSSSWE                         M     M                        QWWWWWE  QWWWWE                 QWWWWE           .                                                                                                                                           J                   ASD                          ',
'SSSSSD                                                  QWE   ASSSSSD  ASSSSD   O    L    .  OASSSSD                                                                      J                                                     QWE               ,        .                   ZXC                          ',
'SSSSSD                    O  K M   K M  O               ASD   ZXXXXXC  ZXXXXC    QWWWWWWWWWWWWASSSSD                         ,  M  ,  M  ,  M                                                                                   ASD              QWE      QWE           J                                   ',
'SSSSSD                     QWWWWWWWWWWWE                ZXC                      ASSSSSSSSSSSSSSSSSD           J        QWWWWWWWWWWWWWWWWWWWWWWWWWE                                                                          M  ZXC     .        ASD      ASD                                               ',
'SSSSSD                     ASSSSSSSSSSSD            QWE                          ASSSSSSSSSSSSSSSSSD                    ASSSSSSSSSSSSSSSSSSSSSSSSSD                                                                                              ZXC      ZXC           .                                   ',
'SSSSSD                     ZXXXXXXXXXXXC            ASD                          ZXXXXXXXXXXXXXXXXXC                    ASSSSSSSSSSSSSSSSSSSSSSSSSD                  M    .                                                 QWE         J                              QWE                                  ',
'SSSSSD    U  O   L   O                              ZXC                                                        .M       ASSSSSSSSSSSSSSSSSSSSSSSSSD              QWWWWWWWWWWWWWWE                                           ASD             QWE                        ASD                                  ',
'SSSSSD    QWWWWWWWWWE                           QWE                                                           RTTTY     ASSSSSSSSSSSSSSSSSSSSSSSSSD              ASSSSSSSSSSSSSSD                                       M   ZXC             ASD                        ZXC                     I            ',
'SSSSSD    ASSSSSSSSSD            M     M        ASD                                            M  M           FGGGH     ASSSSSSSSSSSSSSSSSSSSSSSSSD        M     ASSSSSSSSSSSSSSD                                                           ZXC                 QWE                                         ',
'SSSSSD    ASSSSSSSSSD                           ZXC                                            RTTTY    M     FGGGH     ASSSSSSSSSSSSSSSSSSSSSSSSSD              ASSSSSSSSSSSSSSD                                      QWE              .                       ASD                                         ',
'SSSSSD    ASSSSSSSSSD   O    L   M L   M  L  O                                                 FGGGH       RTTAGGGH     ASSSSSSSSSSSSSSSSSSSSSSSSSDO    L  M L  OASSSSSSSSSSSSSSD                                      ASD             QWE                      ZXC                     QWWWE               ',
'SSSSSD    ASSSSSSSSSD    RTTTTTTTTTTTTTTTTTTY                            O    L  L    L   O    FGGGHO  L  OFGGGGGGH     ASSSSSSSSSSSSSSSSSSSSSSSSSDWWWWWWWWWWWWWWASSSSSSSSSSSSSSD                                      ZXC             ASD                                              ASSSD               ',
'SSSSSD    ASSSSSSSSSD    ASSSSSSSSSSSSSSSSSSD                             RTTTTTTTTTTTTTTY   RTFGGGHTTTTTTTFGGGGGGH     ASSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD         O          K        K      O                 ZXC                                              ZXXXC               ',
'SSSSSD    ASSSSSSSSSD    ASSSSSSSSSSSSSSSSSSD                             FGGGGGGGGGGGGGGH   FGGGGGGGGGGGGGSGGGGGGH     ASSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD          QWWWWWWWWWWWWWWWWWWWWWWWWE                                                                                       ',
'ZXXXXC    ZXXXXXXXXXC    ZXXXXXXXXXXXXXXXXXXC                             VBBBBBBBBBBBBBBN   VBBBBBBBBBBBBBBBBBBBBN     ZXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXC          ASSSSSSSSSSSSSSSSSSSSSSSSD                                                                                       '

]

level3_map = [
'QWWWE                                                                                                                                                                                                                                                                                                    QWW',
'SSSSD                                                                                                                                                                                                                                                                                                    ASS',
'SSSSD                                                                                                                                                                                                                                                                      QWE  QWE                      ASS',
'SSSSD                                                                                                                                                                   .                                                                                             QWE  ASD  ASD                      ASS',
'SSSSD                                                                   .                                                                            M                                      .                                                                         ASD  ZXC  ZXC  RTTTTTTTTTTY      I ASS',
'SSSSD                                O  M K  M  K  M  K  O                                   O  L   O                                                                                                                                                            QWE  ZXC            FSSSSSSSSSSS    5   ASS',
'SSSSD                                 QWWWWWWWWWWWWWWWWWE                                     QWWWWE                                                                                                                                                             ASD                 FSSSSSSSSSSS    QWWWASS',
'SSSSD            O    L  LM L  O      ASSSSSSSSSSSSSSSSSD                                     ASSSSD                          .        O  L     K   M L  O                    QWE           J     QWE                                                            ZXC                 FSSSSSSSSSSS    ASSSSSS',
'SSSSD             QWWWWWWWWWWWE       ASSSSSSSSSSSSSSSSSD               J                  M  ASSSSD                                     QWWWWWWWWWWWWWWWE              J     ASD                 ASD      M                                                                         FSSSSSSSSSSS    ASSSSSS',
'SSSSD             ZASSSSSSSSSDC       ZXXXXXXXXXXXXXXXXXC            M                        ASSSSD                                     ZFSSSSSSSSSSSSSSD                    ZXC           .     ZXC                                                       QWWE                     FSSSSSSSSSSS    ASSSSSS',
'SSSSD     U        ASSSSSSSSSD                                                             QWWASSSSD                                     FSSSSSSSSSSSSSSD               .                   QWE            QWE                                              ASSDO     L       O      FSSSSSSSSSSS    ASSSSSS',
'SSSSD    QWWWWWWWWWWWESSSSSSSD                                 O  L  M  .    K    L  K  LOASSASSSSDO   K     O                J      QWWWWFSSSSSSSSSSSSSSD              QWE           M     ASD            ASD                                              ASSDWWWWWWWWWWWWWE       FSSSSSSSSSSS    ASSSSSS',
'SSSSD    ASSSSSSSSSSSDSSSSSSSD                                  QWWWWWWWWWWWWWWWWWWWWWWWWWWWWWASSSSDWWWWWWWEE                        ZFSSSSSSSSSSSSSSSSSSD       M      ASD                 ZXC            ZXC                                              ASSSSSSSSSSSSSSSSD       FSSSSSSSSSSS    ASSSSSS',
'SSSSD    ASSSSSSSSSSSDSSSSSSSD                                  ZFSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSHC                         FSSSSSSSSSSSSSSSSSSD              ZXC         QWE                                                                     ZXXXXXXXXXXXXXXXXC   RTTTFSSSSSSSSSSS    ASSSSSS',
'SSSSD    ASSSSSSSSSSSDSSSSSSSD                                   FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH           O  L   .    L OFSSSSSSSSSSSSSSSSSSD      QWE                 ASD                                  M  O    K    L     K     O                              FSSSSSSSSSSSSSSS    ASSSSSS',
'SSSSD    ASSSSSSSSSSSDSSSSSSSD                                   FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH            QWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSD      ASD                 ZXC                                      RTTTTTTTTTTTTTTTTTTTT                               FSSSSSSSSSSSSSSS    ASSSSSS',
'SSSSD    ASSSSSSSSSSSDSSSSSSSD      O      L         L    O      FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH            ZFSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD      ZXC                                             O    L   M  OFGGGGGGGGGGGGGGGGGGGGO     K                       OFSSSSSSSSSSSSSSS    ASSSSSS',
'SSSSD    ASSSSSSSSSSSDSSSSSSSD       RTTTTTTTTTTTTTTTTTTTY       FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH             FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                                                       RTTTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTYSSSSSSSSSSS    ASSSSSS',
'SSSSD    ASSSSSSSSSSSDSSSSSSSD       VFGGGGGGGGGGGGGGGGGHN       FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH             FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                                                       VFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGHSSSSSSSSSSS    ASSSSSS',
'SSSSD    ASSSSSSSSSSSDSSSSSSSD        FGGGGGGGGGGGGGGGGGH        FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH             FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                                                        FGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGHSSSSSSSSSSS    ASSSSSS'

]

level4_map = [
'QWWWE                                                                                                                                                                                                                                                                                                                          ',
'ASSSD                                                                                                                                                                                                                 M      M   M                                                                                             ',
'ASSSD                                                                                    QE      .                                                                                                                                                                                                                             ',
'ASSSD                                                                          O   K    OAD              RY                                                                                                    O L  K M   K  M L MK   O                                                                        RTTTTTTTTTTY  ',
'ASSSD                                                                           QWWWWWWWEAD              FH                                                 QWE                                                 QWWWWWWWWWWWWWWWWWWWWWE                        .                                               FGGGGGGGGGFH  ',
'ASSSD                                                         .                 ASSSSSSSSSD              FH                                                 ASD                 .         .                     ASSSSSSSSSSSSSSSSSSSSSD                                                                      RTTGGGGGGGGGFH  ',
'ASSSD                                                                           ASSSSSSSSSD      J       FH                                                 ZXC                                                 ZXXXXXXXXXXXXXXXXXXXXXC                                                                      FGGGGGGGGGGGFH  ',
'ASSSDWWWE                                                                       ASSSSSSSSSD              FH                                                                                                                                                                                                RTTGGGGGGGGGGGFH  ',
'ASSSSSSSD                                  .                                    ASSSSSSSSSDOL M  .  M L OFH                                                                     J                    QE                                                                                                  RTTGGGGGGGGGGGGGFH    ',
'ASSSSSSSD                                                                     QWASSSSSSSSSHTTTTTTTTTTTTTTFH                                      QWE                                                 ZC                                                        J                                         FGGGGGGGGGGGGGGGFH    ',
'ASSSSSSSD                                              QE                     ZXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                      ASD   .      .                           J                                                                                                            RTTGGGGGGGGGGGGGGGFH 6   ',
'ASSSSSSSD                                              ZC                                                                                        ZXC                                                                          RTY                      O   L   .    L  O                               RTTGGGGGGGGGGGGGGGGGFH  ',
'ASSSSSSSD         U                        J                  J  QE                                                                                                         O   .  K     .  O                                 FGH                       QWWWWWWWWWWWWWE                                FGGGGGGGGGGGGGGGGGGGFH  ',
'ASSSSSSSD        QWWWWWWWWWWWWWE                                 ZC                                              O  M K     K M K   K   O                                    QWWWWWWWWWWWWWWE                                 FGH                       FGGGGGGGGGGGGGD                              RTTGGGGGGGGGGGGGGGGGGGFH  ',
'ASSSSSSSD        ASSSSSSSSSSSSSD                                                                                  QWWWWWWWWWWWWWWWWWWWWWWE             J      J            M ASSSSSSSSSSSSSSD                                 FGHTTTTTY                 FGGGGGGGGGGGGGD                            RTTGGGGGGGGGGGGGGGGGGGGGFH  ',
'ASSSSSSSD        ASSSSSSSSSSSSSD                              .                                                   FSSSSSSSSSSSSSSSSSSSSSSD                                   ASSSSSSSSSSSSSSD                                 FGGGGGGGH                 FGGGGGGGGGGGGGD                            FGGGGGGGGGGGGGGGGGGGGGGGFH  ',
'ASSSSSSSD        ASSSSSSSSSSSSSD                QE                                                              RTFSSSSSSSSSSSSSSSSSSSSSSD                                 M ASSSSSSSSSSSSSSD                                 FGGGGGGGHO  L M      M   OFGGGGGGGGGGGGGD                          RTTGGGGGGGGGGGGGGGGGGGGGGGFH  ',
'ASSSSSSSD        ASSSSSSSSSSSSSD                ZC                       O L   L   K   L    L    O              FGGSSSSSSSSSSSSSSSSSSSSSSD     O  L  K .L   K . L   K   L OQWASSSSSSSSSSSSSSD                                 FGGGGGGGHTTTTTTTTTTTTTTTTTFGGGGGGGGGGGGGD       QE        QE     RTTGGGGGGGGGGGGGGGGGGGGGGGGGFH I ',
'ASSSSSSSD        ASSSSSSSSSSSSSD      QE                                  RTTTTTTTTTTTTTTTTTTTTTY       RTTTTTTTTTGSSSSSSSSSSSSSSSSSSSSSSD      QWWWWWWWWWWWWWWWWWWWWWWWWWWASSSSSSSSSSSSSSSSD                                 FGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGD       ZC        ZC     FGGGGGGGGGGGGGGGGGGGGGGGGGGGFHRTF',
'ASSSSSSSD        ASSSSSSSSSSSSSD      ZC   .                              FGGGGGGGGGGGGGGGGGGGGGH       FGGGGGGGGGGSSSSSSSSSSSSSSSSSSSSSSD      ASSSSSSSSSSSSSSSSSSSSSSSSSSASSSSSSSSSSSSSSSSD                                 FGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGD                        FGGGGGGGGGGGGGGGGGGGGGGGGGGGFHFGG'

]


final_level_map = [
'RTY                                                    RTY',
'FGH                                                    FGH',
'FGHY                                                  RFGH',
'FSDH                                                  FFSD',
'FGHH                                                  FFGH',
'FGHD                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH  U                       +                       FFGH',
'FGHHRTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTYFFGH',
'FGHHFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGHFFGH',
'FGHHFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGHFFGH',
'VBHHVBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBNVVBN'

]

tile_size = 26
screen_width = 1000
screen_height = 520
current_level = 0