level0_map =[
'                                                                     M                                                  ',
'                                                        O  M  M   L  M O                                                ',
'Y                                                        QWWWWWWWWWWWWE                                                 ',
'STTY                                                     ASSSSSSSSSSSSD                                                 ',
'SSSGTY                                 M   M             ASSSSSSSSSSSSD                                                 ',
'SSSGSSTY                                                 ZSSSSSSSSSSSSD                                                 ',
'SSSGSSSD               O  M L O    O   M   M  MK O        ZSSSSSSSSSSSD                                                 ',
'SSSGSSSD                QWWWWE      RTTTTTTTTTTTTY         ZSSSSSSSSSSD                                                 ',
'SSSGSSSD                ASSSSD    RTSSSSSSSSSSSSSH          ZSSSSSSSSSC                                                 ',
'SSSGSSSD                ZXXXXC    FSSSSSSSSSSSSSSH           XXXXXXXXC              O    L    L  L  O                   ',
'SSSGSSSD                          VSSSSSSSSSSSSSSH                                   QWWWWWWWWWWWWWE                    ',
'SSGGSSSD                           VXXXXXXXXXXXXXC                                   ASSSSSSSSSSSSSD                    ',
'SSGGSSSD      O L M L  O                                                             ASSSSSSSSSSSSSD            O   I  O',
'SSGGSSSD       RTTTTTTY O  L   O                                                     ASSSSSSSSSSSSSC             RTTTTY ',
'SSGGSSSD U     FGGGGGGH  QWWWWE  O   L   O                           O  L   L     O  ASSSSSSSSSSSSC              VGGGGN ',
'SSGGSSSDQWWE   FGGGGGGH  ASSSSD   RTTTTTY                             QWWWTTTTTTTY   ASSSSSSSSSSSC                VBBN  ',
'SSGGSSSDASSD   FGGGGGGH  ZXXXXC   FGGGGGH                            RSSSSSSGGGGGH   ASSSSSSSSSSC                       ',
'SSGGSSSDASSD   FGGGGGGH           FGGGGGH O   L   L    L  ML  O     RSSSSSSSSSGGGH   ASSSSSSSSSC                        ',
'SSGGSSSDASSD   FGGGGGGH           FGGGGGH  RTTTTTTTTTTTTTTTTTY      FSSSSSSSSSGGGH   ASSSSSSSSC                         ',
'ZXXXXXXCZXXC   VBBBBBBN           VBBBBBN  FGGGGGGGGGGGGGGGGGH      FSSSSSSSSGGGGH   VXXXXXXXC                          ',
'ZXXXXXXCZXXC   VBBBBBBN           VBBBBBN  FGGGGGGGGGGGGGGGGGH      FSSSSSSSSGGGGH   VXXXXXXXC                          '
]

level1_map = [                                                                                                                                                                                                                                                                                                          
'E                                                                                                                                                                                                                                                                                                                ',
'DE                                                                                              O    M OO  ML  OO  M   OO  M   O    O   L  O                                                                                                                                                                    ',
'SDE                                              O      M          M                O            QWWWWE  QWWWWE  QWWWWE  QWWWWE      QWWWWE                                          .                                                                                                                          ',                                                                                
'SSDE                                              RTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTY             ASSSSD  ASSSSD  ASSSSD  ASSSSD      ASSSSD                        M                     M                                                                                                                      ',                                                                                
'SSSDE                                             FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY            ZXXXXC  ZXXXXC  ZXXXXC  ZXXXXC      ZXXXXC      O   L    M     K      L    O                            RTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTY                           ',                                                                                
'SSSSDQWWWWE                                       FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                             RTTTWWWWWWWWWWWWWWWWWWWWWE                 .          ASSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                           ',                                                                                
'SSSSDASSSSD                               .  .    FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                           RASSSSSSSSSSSSSSSSSSSSSSSSD    O K O                   RSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                           ',                                                                                
'SSSSDASSSSD                                       FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                          ASSSSSSSSSSSSSSSSSSSSSSSSSD     QWE J                  FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                    .      ',                                                                                
'SSSSDASSSSD                                  M    FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                         ASSSSSSSSSSSSSSSSSSSSSSSSSD     ASD                    FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                           ',                                                                                
'SSSSDASSSSD                               J       FSSSSSSSSSSSSSSSSSSSSSSSSSSBBBBBBSSSSSD                                                         ASSSSSSSSSSSSSSSSSSSSSSSSSD     ZXC                    FSSSSSSSSXXXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                           ',                                                                                
'SSSSDASSSSD                                       VSSSSSSSSSSSSSSSSSSSSSSSSSN      ZSSSSD        QE                                               ASSSSSSSSSSSSSSSSSSSSSSSSSD         . O K O            FSSSSSSXC   ZXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                           ',                                                                                
'SSSSDASSSSD      U  O    M         O      M  J     VSSSSSSSSSSSSSSSSSSSSSSSN        ZXXXC        ZC                                               ASSSSSSSSSSSSSSSSSSSSSSSSSD            QWE  J          FSSSSSD       ZXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                           ',                                                                                
'SSSSDASSSSD    QWWE QWWWWWWWWWWWWWE                 VSSSSSSSSSSSSSSSSSSSSSN                                                  O      L     M    O  ASSSSSSSSSSSSSSSSSSSSSSSSSD            ASD             FSSSSSSY        ZXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXSSSH                    J  I   ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD O     .  . O     VBBBBBBBBBBBBBBBBBBBN                                                    RWTWTTWTTTWWWTTTY   ASSSSSSSSSSSSSSSSSSSSSSSSSD            ZXC             VSSSSSSSY         ZXXXXXXXXXXXXXXXXXXXXXXXSSSXXXXSSSXXXXXXXXXXXXXXXXXXC  ZSSH                           ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  QWWWWWWWWE                                                              O    M  L    O   FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                  O K O      VBBBBBBC                                 ZXC    ZXC                      ZXC    O      L  M   O        ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  ASSSSSSSSDE                                              O    L M  O     QWWWWWWWWWWE    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                 . QWE                                                                                        RTTTTTWWWWWWE         ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  ASSSSSSSSSD                                               RTTWWWWWE      ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                   ASD                                                                                       RFSSSSSSSSSSSD         ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  ASSSSSSSSSCO    L    O       L   M       L   M      O    RSSSSSSSSD      ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                   ZXC                   M                 M             M                                  RFSSSSSSSSSSSSD  .      ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  ZSSSSSSSSC  QWWWWTTTY  RTTTTTTTTTTTTTTTTTTTTTTTTTTTY     FSSSSSSSSH      ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                        O     L   OO        L         L          O O        L    O                         RFSSSSSSSSSSSSSD         ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD   ZXXXXXXC   FGGGGGGGH  FSSSSSSSSSSSSSSSSSSSSSSSSSSSH     FSSSSSSSSH      ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                         QWWWWTTTY  RTTTTTTTTTTTTTTTTTTTTTTTTTTTY   RTTTTTTTTTTTY        M       M        RFSSSSSSSSSSSSSSD         ',                                                                                
'                                                                                                              ZXXXXXXXXXXC    VBBBBBBBBBBBBBBBN   VBXXXXXXXXXXXXXXXXXXXXXXXXC                         AGGGGGGGH  FSSSSSSSSSSSSSSSSSSSSSSSSSSSH   FSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTFSSSSSSSSSSSSSSSD         '                                                                                                                                                                    
]

level2_map = [                                                                                                                                                                                                                                                                                                          
'E                                                                                                                                                                                                                                                                                                                ',
'DE                                                                                              O    M OO  ML  OO  M   OO  M   O    O   L  O                                                                                                                                                                    ',
'SDE                                              O      M          M                O            QWWWWE  QWWWWE  QWWWWE  QWWWWE      QWWWWE                                          .                                                                                                                          ',                                                                                
'SSDE                                              RTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTY             ASSSSD  ASSSSD  ASSSSD  ASSSSD      ASSSSD                        M                     M                                                                                                                      ',                                                                                
'SSSDE                                             FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY            ZXXXXC  ZXXXXC  ZXXXXC  ZXXXXC      ZXXXXC      O   L    M     K      L    O                            RTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTY                           ',                                                                                
'SSSSDQWWWWE                                       FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                             RTTTWWWWWWWWWWWWWWWWWWWWWE                 .          ASSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                           ',                                                                                
'SSSSDASSSSD                               .  .    FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                           RASSSSSSSSSSSSSSSSSSSSSSSSD    O K O                   RSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                           ',                                                                                
'SSSSDASSSSD                                       FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                          ASSSSSSSSSSSSSSSSSSSSSSSSSD     QWE J                  FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                    .      ',                                                                                
'SSSSDASSSSD                                  M    FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                         ASSSSSSSSSSSSSSSSSSSSSSSSSD     ASD                    FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                           ',                                                                                
'SSSSDASSSSD                               J       FSSSSSSSSSSSSSSSSSSSSSSSSSSBBBBBBSSSSSD                                                         ASSSSSSSSSSSSSSSSSSSSSSSSSD     ZXC                    FSSSSSSSSXXXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                           ',                                                                                
'SSSSDASSSSD                                       VSSSSSSSSSSSSSSSSSSSSSSSSSN      ZSSSSD        QE                                               ASSSSSSSSSSSSSSSSSSSSSSSSSD         . O K O            FSSSSSSXC   ZXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                           ',                                                                                
'SSSSDASSSSD      U  O    M         O      M  J     VSSSSSSSSSSSSSSSSSSSSSSSN        ZXXXC        ZC                                               ASSSSSSSSSSSSSSSSSSSSSSSSSD            QWE  J          FSSSSSD       ZXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                           ',                                                                                
'SSSSDASSSSD    QWWE QWWWWWWWWWWWWWE                 VSSSSSSSSSSSSSSSSSSSSSN                                                  O      L     M    O  ASSSSSSSSSSSSSSSSSSSSSSSSSD            ASD             FSSSSSSY        ZXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXSSSH                    J  I   ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD O     .  . O     VBBBBBBBBBBBBBBBBBBBN                                                    RWTWTTWTTTWWWTTTY   ASSSSSSSSSSSSSSSSSSSSSSSSSD            ZXC             VSSSSSSSY         ZXXXXXXXXXXXXXXXXXXXXXXXSSSXXXXSSSXXXXXXXXXXXXXXXXXXC  ZSSH                           ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  QWWWWWWWWE                                                              O    M  L    O   FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                  O K O      VBBBBBBC                                 ZXC    ZXC                      ZXC    O      L  M   O        ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  ASSSSSSSSDE                                              O    L M  O     QWWWWWWWWWWE    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                 . QWE                                                                                        RTTTTTWWWWWWE         ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  ASSSSSSSSSD                                               RTTWWWWWE      ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                   ASD                                                                                       RFSSSSSSSSSSSD         ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  ASSSSSSSSSCO    L    O       L   M       L   M      O    RSSSSSSSSD      ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                   ZXC                   M                 M             M                                  RFSSSSSSSSSSSSD  .      ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD  ZSSSSSSSSC  QWWWWTTTY  RTTTTTTTTTTTTTTTTTTTTTTTTTTTY     FSSSSSSSSH      ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                        O     L   OO        L         L          O O        L    O                         RFSSSSSSSSSSSSSD         ',                                                                                
'SSSSDASSSSD    ASSD ASSSSSSSSSSSSSD   ZXXXXXXC   FGGGGGGGH  FSSSSSSSSSSSSSSSSSSSSSSSSSSSH     FSSSSSSSSH      ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                         QWWWWTTTY  RTTTTTTTTTTTTTTTTTTTTTTTTTTTY   RTTTTTTTTTTTY        M       M        RFSSSSSSSSSSSSSSD         ',                                                                                
'                                                                                                              ZXXXXXXXXXXC    VBBBBBBBBBBBBBBBN   VBXXXXXXXXXXXXXXXXXXXXXXXXC                         AGGGGGGGH  FSSSSSSSSSSSSSSSSSSSSSSSSSSSH   FSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTFSSSSSSSSSSSSSSSD         '                                                                                                                                                                    
]

level3_map = [
'W                                                                                         .                                                                                                                                                                .                                                ',
'S                                                                                                                                                                                                                                                                                                           ',
'S                                                                                                M                                                                        .                                                                                                                                 ',
'SWE                                                                                       J                                                                                                                                                                             .                                   ',
'SSSE                                                           M   M    M  M           M         M                                                                                                                               M                                             QWE                          ',
'SSSSWE                         M     M                        QWWWWWE  QWWWWE                 QWWWWE           .                                                                                                                                           J                   ASD                          ',
'SSSSSD                                                  QWE   ASSSSSD  ASSSSD   O    L    .  OASSSSD                                                                      J                                                     QWE               ,        .                   ZXC                          ',
'SSSSSD                    O  K M   K M  O               ASD   ZXXXXXC  ZXXXXC    QWWWWWWWWWWWWASSSSD                         ,  M  ,  M  ,  M                                                                                   ASD              QWE      QWE           J                                   ',
'SSSSSD                     QWWWWWWWWWWWE                ZXC                      ASSSSSSSSSSSSSSSSSD           J        QWWWWWWWWWWWWWWWWWWWWWWWWWE                                                                          M  ZXC     .        ASD      ASD                                               ',
'SSSSSD                     ASSSSSSSSSSSD            QWE                          ASSSSSSSSSSSSSSSSSD                    ASSSSSSSSSSSSSSSSSSSSSSSSSD                                                                                              ZXC      ZXC           .                                   ',
'SSSSSD                     ZXXXXXXXXXXXC            ASD                          ZXXXXXXXXXXXXXXXXXC                    ASSSSSSSSSSSSSSSSSSSSSSSSSD                  M    .                                                 QWE         J                              QWE                                  ',
'SSSSSD    U  O   L   O                              ZXC                                                        .M       ASSSSSSSSSSSSSSSSSSSSSSSSSD              QWWWWWWWWWWWWWWE                                           ASD             QWE                        ASD                                  ',
'SSSSSD    QWWWWWWWWWE                           QWE                                                           RTTTY     ASSSSSSSSSSSSSSSSSSSSSSSSSD              ASSSSSSSSSSSSSSD                                       M   ZXC             ASD                        ZXC                     I            ',
'SSSSSD    ASSSSSSSSSD            M     M        ASD                                            M  M           FGGGH     ASSSSSSSSSSSSSSSSSSSSSSSSSD        M     ASSSSSSSSSSSSSSD                                                           ZXC                 QWE                                         ',
'SSSSSD    ASSSSSSSSSD                           ZXC                                            RTTTY    M     FGGGH     ASSSSSSSSSSSSSSSSSSSSSSSSSD              ASSSSSSSSSSSSSSD                                      QWE              .                       ASD                                         ',
'SSSSSD    ASSSSSSSSSD   O    L   M L   M  L  O                                                 FGGGH       RTTAGGGH     ASSSSSSSSSSSSSSSSSSSSSSSSSDO    L  M L  OASSSSSSSSSSSSSSD                                      ASD             QWE                      ZXC                     QWWWE               ',
'SSSSSD    ASSSSSSSSSD    RTTTTTTTTTTTTTTTTTTY                            O    L  L    L   O    FGGGHO  L  OFGGGGGGH     ASSSSSSSSSSSSSSSSSSSSSSSSSDWWWWWWWWWWWWWWASSSSSSSSSSSSSSD                                      ZXC             ASD                                              ASSSD               ',
'SSSSSD    ASSSSSSSSSD    ASSSSSSSSSSSSSSSSSSD                             RTTTTTTTTTTTTTTY   RTFGGGHTTTTTTTFGGGGGGH     ASSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD         O          K        K      O                 ZXC                                              ZXXXC               ',
'SSSSSD    ASSSSSSSSSD    ASSSSSSSSSSSSSSSSSSD                             FGGGGGGGGGGGGGGH   FGGGGGGGGGGGGGSGGGGGGH     ASSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD          QWWWWWWWWWWWWWWWWWWWWWWWWE                                                                                       ',
'ZXXXXC    ZXXXXXXXXXC    ZXXXXXXXXXXXXXXXXXXC                             VBBBBBBBBBBBBBBN   VBBBBBBBBBBBBBBBBBBBBN     ZXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXC          ASSSSSSSSSSSSSSSSSSSSSSSSD                                                                                       '

]

final_level_map = [
'RTY                                                    RTY',
'FGH                                                    FGH',
'FGHY                                                  RFGH',
'FSDH                                                  FFSD',
'FGHH                                                  FFGH',
'FGHD                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH                                                  FFGH',
'FGHH  U                                      +        FFGH',
'FGHHRTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTYFFGH',
'FGHHFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGHFFGH',
'FGHHFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGHFFGH',
'VBHHVBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBNVVBN'

]

tile_size = 26
screen_width = 1000
screen_height = 520
current_level = 0