level1_map =[
'                                                                     M                                                  ',
'                                                        O  M  M   L  M O                                                ',
'Y                                                        QWWWWWWWWWWWWE                                                 ',
'STTY                                                     ASSSSSSSSSSSSD                                                 ',
'SSSGTY                                 M   M             ASSSSSSSSSSSSD                                                 ',
'SSSGSSTY                                                 ZSSSSSSSSSSSSD                                                 ',
'SSSGSSSD               O  M L O    O   M   M  MK O        ZSSSSSSSSSSSD                                                 ',
'SSSGSSSD                QWWWWE      RTTTTTTTTTTTTY         ZSSSSSSSSSSD                                                 ',
'SSSGSSSD                ASSSSD    RTSSSSSSSSSSSSSH          ZSSSSSSSSSC                                                 ',
'SSSGSSSD                ZXXXXC    FSSSSSSSSSSSSSSH           XXXXXXXXC              O    L    L  L  O                   ',
'SSSGSSSD                          VSSSSSSSSSSSSSSH                                   QWWWWWWWWWWWWWE                    ',
'SSGGSSSD                           VXXXXXXXXXXXXXC                                   ASSSSSSSSSSSSSD                    ',
'SSGGSSSD      O L M L  O                                                             ASSSSSSSSSSSSSD            O   I  O',
'SSGGSSSD       RTTTTTTY O  L   O                                                     ASSSSSSSSSSSSSC             RTTTTY ',
'SSGGSSSD U     FGGGGGGH  QWWWWE  O   L   O                           O  L   L     O  ASSSSSSSSSSSSC              VGGGGN ',
'SSGGSSSDQWWE   FGGGGGGH  ASSSSD   RTTTTTY                             QWWWTTTTTTTY   ASSSSSSSSSSSC                VBBN  ',
'SSGGSSSDASSD   FGGGGGGH  ZXXXXC   FGGGGGH                            RSSSSSSGGGGGH   ASSSSSSSSSSC                       ',
'SSGGSSSDASSD   FGGGGGGH           FGGGGGH O   L   L    L  ML  O     RSSSSSSSSSGGGH   ASSSSSSSSSC                        ',
'SSGGSSSDASSD   FGGGGGGH           FGGGGGH  RTTTTTTTTTTTTTTTTTY      FSSSSSSSSSGGGH   ASSSSSSSSC                         ',
'ZXXXXXXCZXXC   VBBBBBBN           VBBBBBN  FGGGGGGGGGGGGGGGGGH      FSSSSSSSSGGGGH   VXXXXXXXC                          ',
'ZXXXXXXCZXXC   VBBBBBBN           VBBBBBN  FGGGGGGGGGGGGGGGGGH      FSSSSSSSSGGGGH   VXXXXXXXC                          '
]

level0_map = [
'E                                                                                                                                                                                                                                                                                                       ',                                                                                         
'DE                                                                                                                                                                                                                                                                                                       ',                                                                                        
'SDE                                                                                       QWWWWE  QWWWWE  QWWWWE  QWWWWE  QWWWWE      QWWWWE                                                                                                                                                            ',                                                                                         
'SSDE                                              RTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTY      ASSSSD  ASSSSD  ASSSSD  ASSSSD  ASSSSD      ASSSSD                                                                                                                                                            ',                                                                                         
'SSSDE                                             FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY     ZXXXXC  ZXXXXC  ZXXXXC  ZXXXXC  ZXXXXC      ZXXXXC                                                              RTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTY                  ',                                                                                         
'SSSSDQWWWWE                                       FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                             RTTTWWWWWWWWWWWWWWWWWWWWWE                             ASSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                  ',                                                                                         
'SSSSDASSSSD                                       FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                           RASSSSSSSSSSSSSSSSSSSSSSSSD                            RSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                  ',                                                                                         
'SSSSDASSSSD                                       FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                          ASSSSSSSSSSSSSSSSSSSSSSSSSD     QWE                    FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                  ',                                                                                         
'SSSSDASSSSD                                       FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSDY                                                         ASSSSSSSSSSSSSSSSSSSSSSSSSD     ASD                    FSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                  ',                                                                                         
'SSSSDASSSSD                                       FSSSSSSSSSSSSSSSSSSSSSSSSSSBBBBBBSSSSSD                                                         ASSSSSSSSSSSSSSSSSSSSSSSSSD     ZXC                    FSSSSSSSSXXXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH                  ',                                                                                         
'SSSSDASSSSD                                       VSSSSSSSSSSSSSSSSSSSSSSSSSN      ZSSSSD   QE                                                    ASSSSSSSSSSSSSSSSSSSSSSSSSD                            FSSSSSSXC   ZXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                  ',                                                                                         
'SSSSDASSSSD      U       123456                    VSSSSSSSSSSSSSSSSSSSSSSSN          ZXC   ZC                                                    ASSSSSSSSSSSSSSSSSSSSSSSSSD            QWE             FSSSSSD       ZXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSD                  ',                                                                                         
'SSSSDASSSSD    QWWWWWWWWWWWWWWWWWWE                 VSSSSSSSSSSSSSSSSSSSSSN                                                                       ASSSSSSSSSSSSSSSSSSSSSSSSSD            ASD             FSSSSSSY        ZXSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXSSSH                  ',                                                                                         
'SSSSDASSSSD    ASSSSSSSSSSSSSSSSSSD                  VBBBBBBBBBBBBBBBBBBBN                                                    RWTWTTWTTTWWWTTTY   ASSSSSSSSSSSSSSSSSSSSSSSSSD            ZXC             VSSSSSSSY         ZXXXXXXXXXXXXXXXXXXXXXXXSSSXXXXSSSXXXXXXXXXXXXXXXXXXC  ZSSH                  ',                                                                                         
'SSSSDASSSSD    ASSSSSSSSSSSSSSSSSSD  QWWWWWWWWE                                                                               FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                             VBBBBBBC                                 ZXC    ZXC                      ZXC                 I',                                                                                         
'SSSSDASSSSD    ASSSSSSSSSSSSSSSSSSD  ASSSSSSSSDE                                                              QWWWWWWWWWWE    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                   QWE                                                                                        RTTTTTWWWWWWE',                                                                                         
'SSSSDASSSSD    ASSSSSSSSSSSSSSSSSSD  ASSSSSSSSSD                     ..........              RTTWWWWWE        ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                   ASD                                                                                       RFSSSSSSSSSSSD',                                                                                         
'SSSSDASSSSD    ASSSSSSSSSSSSSSSSSSD  ASSSSSSSSSC                     ..........             RSSSSSSSSD        ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                   ZXC                                                                                      RFSSSSSSSSSSSSD',                                                                                         
'SSSSDASSSSD    ASSSSSSSSSSSSSSSSSSD  ZSSSSSSSSC  QWWWWTTTY  RTTTTTTTTTTTTTTTTTTTTTTTTTTTY   FSSSSSSSSH        ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                                                                                                           RFSSSSSSSSSSSSSD',                                                                                         
'SSSSDASSSSD    ASSSSSSSSSSSSSSSSSSD   ZXXXXXXC   FGGGGGGGH  FSSSSSSSSSSSSSSSSSSSSSSSSSSSH   FSSSSSSSSH        ASSSSSSSSSSD    FSSSSSSSSSSSSSSSH   ASSSSSSSSSSSSSSSSSSSSSSSSSD                         QWWWWTTTY  RTTTTTTTTTTTTTTTTTTTTTTTTTTTY   RTTTTTTTTTTTY                         RFSSSSSSSSSSSSSSD',                                                                                         
'                                                                                                              ZXXXXXXXXXXC    VBBBBBBBBBBBBBBBN   VBXXXXXXXXXXXXXXXXXXXXXXXXC                         AGGGGGGGH  FSSSSSSSSSSSSSSSSSSSSSSSSSSSH   FSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTFSSSSSSSSSSSSSSSD',                                                                                        
]

tile_size = 26
screen_width = 1000
screen_height = 520
current_level = 0